// Galería de ejercicios con animación, para cambiar la rutina sobre la marcha
// cuando la máquina está ocupada o toca improvisar. URLs comprobadas una a una.
export const GRUPOS = {
  pecho: "Pecho",
  espalda: "Espalda",
  hombro: "Hombro",
  biceps: "Bíceps",
  triceps: "Tríceps",
  pierna: "Pierna",
  gluteo: "Glúteo",
  gemelo: "Gemelo",
  abdomen: "Abdomen"
};

export const CATALOGO = [
  { nombre: "Aperturas con mancuerna", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Fly.gif" },
  { nombre: "Aperturas inclinadas en máquina", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2023/06/Incline-Chest-Fly-Machine.gif" },
  { nombre: "Contractor de pecho (peck deck)", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pec-Deck-Fly.gif" },
  { nombre: "Cruce de polea", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Cable-Crossover.gif" },
  { nombre: "Cruce de polea alta", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/High-Cable-Crossover.gif" },
  { nombre: "Cruce de polea baja", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Low-Cable-Crossover.gif" },
  { nombre: "Press banca", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bench-Press.gif" },
  { nombre: "Press inclinado con barra", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Barbell-Bench-Press.gif" },
  { nombre: "Press inclinado con mancuerna", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Incline-Dumbbell-Press.gif" },
  { nombre: "Press inclinado en máquina", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Lever-Incline-Chest-Press.gif" },
  { nombre: "Pullover", grupo: "pecho", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Pullover.gif" },
  { nombre: "Dominadas", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pull-up.gif" },
  { nombre: "Face pull", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Face-Pull.gif" },
  { nombre: "Jalón al pecho", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif" },
  { nombre: "Jalón frontal en máquina", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/05/Front-Pulldown.gif" },
  { nombre: "Jalón tras nuca", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/08/Cable-Rear-Pulldown.gif" },
  { nombre: "Peso muerto", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Deadlift.gif" },
  { nombre: "Remo alto", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Upright-Row.gif" },
  { nombre: "Remo con barra", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Bent-Over-Row.gif" },
  { nombre: "Remo con mancuerna", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif" },
  { nombre: "Remo gironda (polea sentado)", grupo: "espalda", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Seated-Cable-Row.gif" },
  { nombre: "Elevaciones frontales", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Front-Raise.gif" },
  { nombre: "Elevaciones laterales", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lateral-Raise.gif" },
  { nombre: "Elevaciones laterales en máquina", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/09/Lever-Lateral-Raise.gif" },
  { nombre: "Encogimientos de hombros", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Shrug.gif" },
  { nombre: "Pájaros (deltoide posterior)", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Bent-Over-Lateral-Raise.gif" },
  { nombre: "Press hombro con mancuernas", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif" },
  { nombre: "Press hombro de pie", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2023/09/Standing-Dumbbell-Overhead-Press.gif" },
  { nombre: "Press hombro en multipower", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Smith-Machine-Shoulder-Press.gif" },
  { nombre: "Press militar con barra", grupo: "hombro", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Shoulder-Press.gif" },
  { nombre: "Curl con barra", grupo: "biceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Curl.gif" },
  { nombre: "Curl con mancuernas", grupo: "biceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Curl.gif" },
  { nombre: "Curl concentrado", grupo: "biceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Concentration-Curl.gif" },
  { nombre: "Curl martillo", grupo: "biceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Hammer-Curl.gif" },
  { nombre: "Curl predicador", grupo: "biceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Preacher-Curl.gif" },
  { nombre: "Curl predicador con barra Z", grupo: "biceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Z-Bar-Preacher-Curl.gif" },
  { nombre: "Extensión de tríceps con mancuerna", grupo: "triceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Triceps-Extension.gif" },
  { nombre: "Fondos en banco", grupo: "triceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Bench-Dips.gif" },
  { nombre: "Fondos en paralelas", grupo: "triceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Triceps-Dips.gif" },
  { nombre: "Patada de tríceps", grupo: "triceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Kickback.gif" },
  { nombre: "Tríceps en polea con barra", grupo: "triceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Pushdown.gif" },
  { nombre: "Tríceps en polea con cuerda", grupo: "triceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Rope-Pushdown.gif" },
  { nombre: "Tríceps tras nuca en polea", grupo: "triceps", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/04/Cable-Rope-Overhead-Triceps-Extension.gif" },
  { nombre: "Curl femoral tumbado", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Leg-Curl.gif" },
  { nombre: "Extensión de cuádriceps", grupo: "pierna", imagen: "https://i.pinimg.com/originals/33/24/5f/33245f9b08426eb8d0860f9261111283.gif" },
  { nombre: "Peso muerto rumano", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Romanian-Deadlift.gif" },
  { nombre: "Prensa", grupo: "pierna", imagen: "https://fitcron.com/wp-content/uploads/2021/04/07401301-Sled-45%C2%B0-Leg-Wide-Press_Thighs_720.gif" },
  { nombre: "Sentadilla en multipower", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2024/10/smith-machine-squat.gif" },
  { nombre: "Sentadilla goblet", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2023/01/Dumbbell-Goblet-Squat.gif" },
  { nombre: "Sentadilla hack", grupo: "pierna", imagen: "https://www.thingys.com.ar/gymapps/tutorial/hack_new.gif" },
  { nombre: "Sentadilla sumo", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2025/04/Bodyweight-Plie-Squat.gif" },
  { nombre: "Zancada hacia atrás cruzada", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2023/09/curtsy-lunge.gif" },
  { nombre: "Zancada pendular", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2025/09/pendulum-lunge.gif" },
  { nombre: "Zancadas con mancuernas", grupo: "pierna", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Lunge.gif" },
  { nombre: "Abducción de cadera", grupo: "gluteo", imagen: "https://gymvisual.com/img/p/1/2/7/1/4/12714.gif" },
  { nombre: "Aducción de cadera en máquina", grupo: "gluteo", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/HIP-ADDUCTION-MACHINE.gif" },
  { nombre: "Hip Thrust", grupo: "gluteo", imagen: "https://gymvisual.com/img/p/5/7/6/1/5761.gif" },
  { nombre: "Hip thrust con barra", grupo: "gluteo", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Barbell-Hip-Thrust.gif" },
  { nombre: "Patada de glúteo en polea", grupo: "gluteo", imagen: "https://www.thingys.com.ar/gymapps/tutorial/gluteos_polea2.gif" },
  { nombre: "Gemelo de pie", grupo: "gemelo", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Standing-Calf-Raise.gif" },
  { nombre: "Gemelo de pie con mancuerna", grupo: "gemelo", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Calf-Raise.gif" },
  { nombre: "Gemelo en prensa", grupo: "gemelo", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/05/Leg-Press-Calf-Raise.gif" },
  { nombre: "Gemelo sentado en máquina", grupo: "gemelo", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Lever-Seated-Calf-Raise.gif" },
  { nombre: "Crunch en polea", grupo: "abdomen", imagen: "https://fitnessprogramer.com/wp-content/uploads/2021/02/Kneeling-Cable-Crunch.gif" },
  { nombre: "Plancha", grupo: "abdomen", imagen: "https://fitnessprogramer.com/wp-content/uploads/2023/07/High-Plank.gif" },
];

const limpiar = (t) => t.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();

// Busca por nombre, ignorando tildes y mayúsculas, y filtra por grupo.
export const buscar = (texto, grupo) =>
  CATALOGO.filter(
    (e) => (!grupo || e.grupo === grupo) && (!texto || limpiar(e.nombre).includes(limpiar(texto))),
  );
